In [ ]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df.head(10)

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,10,12,Thursday,Yes,25.353055,30.015975,1846.391884,8,Off,Off,10.718198,76.316250
1,10,6,Saturday,Yes,28.828129,53.786398,1570.440977,3,On,Off,8.942249,76.781543
2,2,8,Saturday,No,25.168296,40.026548,1632.958668,2,Off,On,2.366881,63.216577
3,12,20,Friday,Yes,24.957368,46.048422,1180.693311,7,On,Off,22.724291,61.424007
4,1,7,Tuesday,No,24.957368,53.316655,1050.317602,8,On,Off,26.817108,78.254288

In [42]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df.head(10).isnull()

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,True
9,False,False,False,False,False,False,False,False,False,False,False,False

In [46]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df.head(10).isnull().sum()

Month                0
Hour                 0
DayOfWeek            0
Holiday              0
Temperature          2
Humidity             0
SquareFootage        0
Occupancy            0
HVACUsage            0
LightingUsage        0
RenewableEnergy      0
EnergyConsumption    2
dtype: int64

In [43]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df.head(10).fillna(0)

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,10,12,Thursday,Yes,25.353055,30.015975,1846.391884,8,Off,Off,10.718198,76.316250
1,10,6,Saturday,Yes,28.828129,53.786398,1570.440977,3,On,Off,8.942249,0.000000
2,2,8,Saturday,No,25.168296,40.026548,1632.958668,2,Off,On,2.366881,63.216577
3,12,20,Friday,Yes,0.000000,46.048422,1180.693311,7,On,Off,22.724291,61.424007
4,1,7,Tuesday,No,0.000000,53.316655,1050.317602,8,On,Off,26.817108,78.254288
5,6,20,Thursday,Yes,23.649274,38.689754,1773.138152,5,Off,On,26.533177,67.079427
6,9,8,Wednesday,No,21.364147,39.979570,1888.756568,0,On,On,9.283064,77.884571
7,6,19,Tuesday,Yes,23.055089,38.218491,1208.172336,1,On,On,22.024764,71.283849
8,11,4,Sunday,No,25.376002,52.233540,1000.512661,4,Off,On,7.478494,0.000000
9,11,15,Monday,Yes,27.558304,35.324520,1206.614730,1,On,On,8.092473,72.802200

In [40]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df["Temperature"]=df["Temperature"].fillna(df["Temperature"].mean())
df.head(10)

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,10,12,Thursday,Yes,25.353055,30.015975,1846.391884,8,Off,Off,10.718198,76.316250
1,10,6,Saturday,Yes,28.828129,53.786398,1570.440977,3,On,Off,8.942249,NaN
2,2,8,Saturday,No,25.168296,40.026548,1632.958668,2,Off,On,2.366881,63.216577
3,12,20,Friday,Yes,24.957368,46.048422,1180.693311,7,On,Off,22.724291,61.424007
4,1,7,Tuesday,No,24.957368,53.316655,1050.317602,8,On,Off,26.817108,78.254288
5,6,20,Thursday,Yes,23.649274,38.689754,1773.138152,5,Off,On,26.533177,67.079427
6,9,8,Wednesday,No,21.364147,39.979570,1888.756568,0,On,On,9.283064,77.884571
7,6,19,Tuesday,Yes,23.055089,38.218491,1208.172336,1,On,On,22.024764,71.283849
8,11,4,Sunday,No,25.376002,52.233540,1000.512661,4,Off,On,7.478494,NaN
9,11,15,Monday,Yes,27.558304,35.324520,1206.614730,1,On,On,8.092473,72.802200

In [56]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df["Temperature"]=df["Temperature"].fillna(df["Temperature"].mode()[0])
df.head(10)

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,10,12,Thursday,Yes,25.353055,30.015975,1846.391884,8,Off,Off,10.718198,76.316250
1,10,6,Saturday,Yes,28.828129,53.786398,1570.440977,3,On,Off,8.942249,NaN
2,2,8,Saturday,No,25.168296,40.026548,1632.958668,2,Off,On,2.366881,63.216577
3,12,20,Friday,Yes,29.998671,46.048422,1180.693311,7,On,Off,22.724291,61.424007
4,1,7,Tuesday,No,29.998671,53.316655,1050.317602,8,On,Off,26.817108,78.254288
5,6,20,Thursday,Yes,23.649274,38.689754,1773.138152,5,Off,On,26.533177,67.079427
6,9,8,Wednesday,No,21.364147,39.979570,1888.756568,0,On,On,9.283064,77.884571
7,6,19,Tuesday,Yes,23.055089,38.218491,1208.172336,1,On,On,22.024764,71.283849
8,11,4,Sunday,No,25.376002,52.233540,1000.512661,4,Off,On,7.478494,NaN
9,11,15,Monday,Yes,27.558304,35.324520,1206.614730,1,On,On,8.092473,72.802200

In [15]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df["Temperature"]=df["Temperature"].fillna(df["Temperature"].mean())
df["Humidity"]=df["Humidity"].fillna(df["Humidity"].mean())
df["EnergyConsumption"]=df["EnergyConsumption"].fillna(df["EnergyConsumption"].mean())
df.drop_duplicates(inplace=True)
print(df)
df.isnull().sum()
df.to_csv("Energy_consumption_dataset_uncleaned.csv",index=False)

      Month  Hour DayOfWeek Holiday  Temperature   Humidity  SquareFootage  \
0        10    12  Thursday     Yes    25.353055  30.015975    1846.391884
1        10     6  Saturday     Yes    28.828129  53.786398    1570.440977
2         2     8  Saturday      No    25.168296  40.026548    1632.958668
3        12    20    Friday     Yes    24.957368  46.048422    1180.693311
4         1     7   Tuesday      No    24.957368  53.316655    1050.317602
...     ...   ...       ...     ...          ...        ...            ...
4995     11    20  Thursday     Yes    29.599400  35.533025    1105.735044
4996      1    10  Thursday     Yes    25.504272  35.883919    1124.708975
4997      8    21   Tuesday      No    24.328898  53.272419    1718.506810
4998      9     4  Thursday      No    24.175753  50.737839    1535.678052
4999      2    20  Saturday     Yes    26.987898  56.785380    1149.656331

      Occupancy HVACUsage LightingUsage  RenewableEnergy  EnergyConsumption  \
0             8       Off           Off        10.718198          76.316250
1             3        On           Off         8.942249          76.781543
2             2       Off            On         2.366881          63.216577
3             7        On           Off        22.724291          61.424007
4             8        On           Off        26.817108          78.254288
...         ...       ...           ...              ...                ...
4995          3        On           Off        10.252285          70.855299
4996          9        On           Off         1.974491          84.906881
4997          0        On           Off         0.006642          69.045556
4998          3        On           Off         7.806679          73.534622
4999          0        On           Off         7.502224          82.560688

     EnergyConsumption_binned
0                      medium
1                      medium
2                         low
3                         low
4                      medium
...                       ...
4995                   medium
4996                     high
4997                   medium
4998                   medium
4999                   medium

[5000 rows x 13 columns]

In [13]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
numeric_cols=df.select_dtypes(include=['int64','float64']).columns
print("numeric cols are found",list(numeric_cols))
if(len(numeric_cols)>0):
    col=numeric_cols[7]
    df[col+"_binned"]=pd.cut(df[col],bins=3,labels=["low","medium","high"])
    print(f"\nBinning applied on column:{col}")
    print(df[[col,col+"_binned"]])
else:
    print("no numeric columns are found")

df.to_csv("Energy_consumption_dataset_uncleaned.csv",index=False)

numeric cols are found ['Month', 'Hour', 'Temperature', 'Humidity', 'SquareFootage', 'Occupancy', 'RenewableEnergy', 'EnergyConsumption']

Binning applied on column:EnergyConsumption
      EnergyConsumption EnergyConsumption_binned
0             76.316250                   medium
1             76.781543                   medium
2             63.216577                      low
3             61.424007                      low
4             78.254288                   medium
...                 ...                      ...
4995          70.855299                   medium
4996          84.906881                     high
4997          69.045556                   medium
4998          73.534622                   medium
4999          82.560688                   medium

[5000 rows x 2 columns]

In [18]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
nums_cols=df.select_dtypes(include=['int64','float64'])
outlier_count={}
for col in nums_cols:
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    iqr=q3-q1
    lb=q1-1.5*iqr
    ub=q3+1.5*iqr
    outliers=df[(df[col]<lb)|(df[col]>ub)]
    outlier_count[col]=len(outliers)
print(outlier_count)
df.to_csv("Energy_consumption_dataset_uncleaned.csv",index=False)

{'Month': 0, 'Hour': 0, 'Temperature': 0, 'Humidity': 0, 'SquareFootage': 0, 'Occupancy': 0, 'RenewableEnergy': 0, 'EnergyConsumption': 0}

In [9]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
numeric_cols=["Month","Hour","Temperature","Humidity","SquareFootage","Occupancy","RenewableEnergy","EnergyConsumption"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
c_cols=["DayOfWeek","Holiday","HVACUsage","LightingUsage"]
for col in c_cols:
    df[col] = df[col].str.strip().str.lower()
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
print(df.head(10))
df.to_csv("Energy_consumption_dataset_uncleaned.csv",index=False)

   Month  Hour  DayOfWeek Holiday  Temperature   Humidity  SquareFootage  \
0     10    12   thursday     yes    25.353055  30.015975    1846.391884
1     10     6   saturday     yes    28.828129  53.786398    1570.440977
2      2     8   saturday      no    25.168296  40.026548    1632.958668
3     12    20     friday     yes    24.957368  46.048422    1180.693311
4      1     7    tuesday      no    24.957368  53.316655    1050.317602
5      6    20   thursday     yes    23.649274  38.689754    1773.138152
6      9     8  wednesday      no    21.364147  39.979570    1888.756568
7      6    19    tuesday     yes    23.055089  38.218491    1208.172336
8     11     4     sunday      no    25.376002  52.233540    1000.512661
9     11    15     monday     yes    27.558304  35.324520    1206.614730

   Occupancy HVACUsage LightingUsage  RenewableEnergy  EnergyConsumption  \
0          8       off           off        10.718198          76.316250
1          3        on           off         8.942249          76.781543
2          2       off            on         2.366881          63.216577
3          7        on           off        22.724291          61.424007
4          8        on           off        26.817108          78.254288
5          5       off            on        26.533177          67.079427
6          0        on            on         9.283064          77.884571
7          1        on            on        22.024764          71.283849
8          4       off            on         7.478494          76.781543
9          1        on            on         8.092473          72.802200

  EnergyConsumption_binned
0                   medium
1                   medium
2                      low
3                      low
4                   medium
5                      low
6                   medium
7                   medium
8                   medium
9                   medium

In [ ]:
import pandas as pd
df=pd.read_csv("Energy_consumption_dataset_uncleaned.csv")
df["DayOfWeek"] = df["DayOfWeek"].astype("category").cat.codes
df["Holiday"] = df["Holiday"].map({"yes": 1, "no": 0})
df["HVACUsage"] = df["HVACUsage"].map({"on": 1, "off": 0})
df["LightingUsage"] = df["LightingUsage"].map({"on": 1, "off": 0})
df["EnergyConsumption_binned"]=df["EnergyConsumption_binned"].map({"low":0,"medium":1,"high":2})
numeric_cols=["Month","Hour","DayOfWeek","Holiday","Temperature","Humidity","SquareFootage","Occupancy","HVACUsage","LightingUsage","RenewableEnergy","EnergyConsumption","EnergyConsumption_binned"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
df[numeric_cols] = (df[numeric_cols] - df[numeric_cols].min()) / (df[numeric_cols].max() - df[numeric_cols].min())
print(df.head(10))
#df.to_csv("Energy_consumption_dataset_uncleaned.csv",index=False)

      Month      Hour  DayOfWeek  Holiday  Temperature      Humidity  \
0  0.818182  0.521739   0.666667      1.0     0.535025  1.657722e-08
1  0.818182  0.260870   0.333333      1.0     0.882842  7.935878e-01
2  0.090909  0.347826   0.333333      0.0     0.516533  3.342081e-01
3  1.000000  0.869565   0.000000      1.0     0.495421  5.352515e-01
4  0.000000  0.304348   0.833333      0.0     0.495421  7.779052e-01
5  0.454545  0.869565   0.666667      1.0     0.364495  2.895786e-01
6  0.727273  0.347826   1.000000      0.0     0.135779  3.326398e-01
7  0.454545  0.826087   0.833333      1.0     0.305024  2.738452e-01
8  0.909091  0.173913   0.500000      0.0     0.537322  7.417448e-01
9  0.909091  0.652174   0.166667      1.0     0.755746  1.772285e-01

   SquareFootage  Occupancy  HVACUsage  LightingUsage  RenewableEnergy  \
0   8.463281e-01   0.888889        0.0            0.0         0.357544
1   5.702308e-01   0.333333        1.0            0.0         0.298264
2   6.327816e-01   0.222222        0.0            1.0         0.078783
3   1.802763e-01   0.777778        1.0            0.0         0.758299
4   4.983137e-02   0.888889        1.0            0.0         0.894915
5   7.730355e-01   0.555556        0.0            1.0         0.885437
6   8.887153e-01   0.000000        1.0            1.0         0.309641
7   2.077699e-01   0.111111        1.0            1.0         0.734950
8   3.254318e-10   0.444444        0.0            1.0         0.249405
9   2.062114e-01   0.111111        1.0            1.0         0.269899

   EnergyConsumption  EnergyConsumption_binned
0           0.501830                       0.5
1           0.511958                       0.5
2           0.216669                       0.0
3           0.177647                       0.0
4           0.544018                       0.5
5           0.300757                       0.0
6           0.535970                       0.5
7           0.392282                       0.5
8           0.511958                       0.5
9           0.425334                       0.5